kind: pipeline
type: docker
name: build-and-upload

platform:
  arch: amd64
  os: linux

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: admin/oscarwonkyse
      tags: latest
      registry: registry:5000

trigger:
  branch:
  - master
