kind: pipeline
type: docker
name: build-and-upload

steps:
- name: telgram-notify
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_chat_id
    message: "oscarwonkyse"

trigger:
  branch:
  - master