kind: pipeline
type: docker
name: build-and-upload

platform:
  arch: amd64
  os: linux

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: localhost:5000/oscarwonkyse
      tags: latest

trigger:
  branch:
  - master