kind: pipeline
type: docker
name: default

steps:
  - name: rsync-copy
    image: drillster/drone-rsync
    settings:
      hosts:
        from_secret: ssh_host
      user:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      exclude: [ "*.md", ".drone.yml" ]
      source: ./
      target: /var/www/oscar/
      recursive: true
      delete: true
