kind: pipeline
type: docker
name: default

steps:
  - name: compress
    image: node:21-alpine
    commands:
      - npm install -g uglify-js clean-css-cli imagemin-cli imagemin-gifsicle
      - find ./ -name '*.js' -exec uglifyjs {} -o {} \;
      - find ./ -name '*.css' -exec cleancss -o {} {} \;
      - find ./ -type f \( -iname \*.png -o -iname \*.jpg -o -iname \*.jpeg -o -iname \*.gif \) -exec imagemin {} --out-dir=$(dirname {}) \;

  - name: rsync-copy
    image: drillster/drone-rsync
    settings:
      hosts:
        from_secret: ssh_host
      user:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      exclude: [ "*.md", ".drone.yml" ]
      source: ./
      target: /var/www/oscar/
      recursive: true
      delete: true
