kind: pipeline
type: docker
name: build-and-upload

platform:
  arch: amd64
  os: linux

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: hub.wonky.se/admin/oscarwonkyse
      tags: latest
      registry: hub.wonky.se

trigger:
  branch:
  - master
